title: Human-computer Incantations A D.J. Frick portfolio
description: A collection of auditory assaults, featuring interactive audio projects, ethical AI development and select visual art projects.
theme: jekyll-theme-minimal
author: DJ Frick
